inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
    - src/*

build:
    nodes:
        php71:
            environment:
                php: '7.1'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: composer test
                        coverage:
                            file: build/phpunit/clover.xml
                            format: php-clover
