language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
 - composer self-update
 - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v

