language: php

php:
  - 7.0
  - 7.1

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
